### ISSUE TITLE
How to set limit of users in one room

### ISSUE THREAD

**Issue by Arjun-Shinojiya** [mmukhin/psitsmike_example_2#3]
Hi Sir, your example is very good to understand. Now I have one question that, is it possible to set a limit of users to join in one room. Like I want only 2 people to do chat in one room.No one can join that room if 2 person is already there.

**Comment by mmukhin** [comment]
Yeah! You can expand the `rooms` array of strings to be an array of objects, something like, `var rooms = [{title: 'room1', maxsize: 2, currentsize: 0}, ..., ...];` 

Then check any time a user requests to go into a room, whether or not there are already 2 people in there, and deny them entry.

**Comment by Arjun-Shinojiya** [comment]
okay ,I got it .Thank you :)
